### ISSUE TITLE
システム・タイマ処理の変更もれ

### ISSUE THREAD

**Issue by moons3925** [ytoyoyama/interface_trykernel#2]
お疲れさまです。
書籍の83ページ

リスト５　システム・タイマ処理の変更

この変更が第４部以降のソースに適用されるべきではないでしょうか？
ソースコードを見る限り、変更もれのようです。

起床待ちでタイムアウト時の処理もれ　のようですから、大きな問題ではないと思いますけど。

ファイル：kernel\systimer.c

ご確認お願いします。

**Comment by ytoyoyama** [comment]
たしかに4部以降の該当ファイルが3部のまま変更されてないようです。
4部では1章ごとにこのファイルに変更が入ります。現状ですとタイムアウト時にエラーコードがE_TMOのところがE_OKになってしまいます。後ほど修正したいと思います。

**Comment by ytoyoyama** [comment]
修正しました
