### ISSUE TITLE
セマフォ解放によるタスク起床について

### ISSUE THREAD

**Issue by kons-9** [ytoyoyama/interface_trykernel#3]
素晴らしい書籍ありがとうございます。自作OSは初めてでしたので、大変勉強になりました。

一点疑問点がございます。
セマフォについて、tk_sig_sem内部のタスクの起床に関してsemidが考慮されていないように感じました。
具体的には、あるsemidが引数で与えられた時、そのsemidを考慮せずにtcb->waisemとsemcb->semcntを比べていると思います。

これを解決するために、タスクがsemidと結びつく必要があると考え、
1. tcbにsemidを追加し、それと比較する
2. semcbでwait_queueを割り振り、その中でタスクの起床を行う(mtkernelの実装はこちらのように思います)
が必要になる気がしました。いかがでしょうか。

**Comment by ytoyoyama** [comment]
たしかに対象セマフォの確認が抜けてました。イベントフラグも同様です。
TryKernelはできる限りシンプルに記述しようとWait Queueを一本化にしたのですが、そこでしくじりました。
1の提案、TCBに待ち対象のオブジェクトのIDを記録し比較することにより対応しようと思います。

**Comment by ytoyoyama** [comment]
本件、イベントフラグも含めて修正しました [0.0.4]
